export const dummyData = {
  location: {
    name: "Itabira",
    region: "Minas Gerais",
    country: "Brazil",
    lat: -19.62,
    lon: -43.22,
    tz_id: "America/Sao_Paulo",
    localtime_epoch: 1701047600,
    localtime: "2023-11-26 22:13",
  },
  current: {
    last_updated_epoch: 1701046800,
    last_updated: "2023-11-26 22:00",
    temp_c: 19,
    temp_f: 66.1,
    is_day: 0,
    condition: {
      text: "Nublado",
      icon: "//cdn.weatherapi.com/weather/64x64/night/119.png",
      code: 1006,
    },
    wind_mph: 2.5,
    wind_kph: 4,
    wind_degree: 133,
    wind_dir: "SE",
    pressure_mb: 1018,
    pressure_in: 30.08,
    precip_mm: 0,
    precip_in: 0,
    humidity: 89,
    cloud: 70,
    feelslike_c: 19,
    feelslike_f: 66.1,
    vis_km: 10,
    vis_miles: 6,
    uv: 1,
    gust_mph: 4.7,
    gust_kph: 7.5,
  },
  forecast: {
    forecastday: [
      {
        date: "2023-11-26",
        date_epoch: 1700956800,
        day: {
          maxtemp_c: 23.5,
          maxtemp_f: 74.3,
          mintemp_c: 16.1,
          mintemp_f: 60.9,
          avgtemp_c: 19.3,
          avgtemp_f: 66.8,
          maxwind_mph: 3.4,
          maxwind_kph: 5.4,
          totalprecip_mm: 0.23,
          totalprecip_in: 0.01,
          totalsnow_cm: 0,
          avgvis_km: 9.7,
          avgvis_miles: 6,
          avghumidity: 81,
          daily_will_it_rain: 1,
          daily_chance_of_rain: 87,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Possibilidade de chuva irregular",
            icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
            code: 1063,
          },
          uv: 4,
        },
        astro: {
          sunrise: "05:04 AM",
          sunset: "06:15 PM",
          moonrise: "05:45 PM",
          moonset: "04:10 AM",
          moon_phase: "Waxing Gibbous",
          moon_illumination: 98,
          is_moon_up: 1,
          is_sun_up: 0,
        },
        hour: [
          {
            time_epoch: 1700967600,
            time: "2023-11-26 00:00",
            temp_c: 17,
            temp_f: 62.5,
            is_day: 0,
            condition: {
              text: "Possibilidade de chuva irregular",
              icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
              code: 1063,
            },
            wind_mph: 1.3,
            wind_kph: 2.2,
            wind_degree: 145,
            wind_dir: "SE",
            pressure_mb: 1019,
            pressure_in: 30.09,
            precip_mm: 0.01,
            precip_in: 0,
            humidity: 91,
            cloud: 100,
            feelslike_c: 17,
            feelslike_f: 62.5,
            windchill_c: 17,
            windchill_f: 62.5,
            heatindex_c: 17,
            heatindex_f: 62.5,
            dewpoint_c: 15.4,
            dewpoint_f: 59.7,
            will_it_rain: 1,
            chance_of_rain: 82,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 2.1,
            gust_kph: 3.5,
            uv: 1,
          },
          {
            time_epoch: 1700971200,
            time: "2023-11-26 01:00",
            temp_c: 16.6,
            temp_f: 61.8,
            is_day: 0,
            condition: {
              text: "Possibilidade de chuva irregular",
              icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
              code: 1063,
            },
            wind_mph: 1.8,
            wind_kph: 2.9,
            wind_degree: 150,
            wind_dir: "SSE",
            pressure_mb: 1018,
            pressure_in: 30.06,
            precip_mm: 0.01,
            precip_in: 0,
            humidity: 93,
            cloud: 100,
            feelslike_c: 16.6,
            feelslike_f: 61.8,
            windchill_c: 16.6,
            windchill_f: 61.8,
            heatindex_c: 16.6,
            heatindex_f: 61.8,
            dewpoint_c: 15.5,
            dewpoint_f: 59.8,
            will_it_rain: 0,
            chance_of_rain: 70,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.2,
            gust_kph: 5.1,
            uv: 1,
          },
          {
            time_epoch: 1700974800,
            time: "2023-11-26 02:00",
            temp_c: 16.5,
            temp_f: 61.6,
            is_day: 0,
            condition: {
              text: "Possibilidade de chuva irregular",
              icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
              code: 1063,
            },
            wind_mph: 1.3,
            wind_kph: 2.2,
            wind_degree: 147,
            wind_dir: "SSE",
            pressure_mb: 1017,
            pressure_in: 30.04,
            precip_mm: 0.01,
            precip_in: 0,
            humidity: 94,
            cloud: 100,
            feelslike_c: 16.5,
            feelslike_f: 61.6,
            windchill_c: 16.5,
            windchill_f: 61.6,
            heatindex_c: 16.5,
            heatindex_f: 61.6,
            dewpoint_c: 15.4,
            dewpoint_f: 59.8,
            will_it_rain: 0,
            chance_of_rain: 62,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 2.4,
            gust_kph: 3.9,
            uv: 1,
          },
          {
            time_epoch: 1700978400,
            time: "2023-11-26 03:00",
            temp_c: 16.4,
            temp_f: 61.6,
            is_day: 0,
            condition: {
              text: "Nublado",
              icon: "//cdn.weatherapi.com/weather/64x64/night/119.png",
              code: 1006,
            },
            wind_mph: 0.9,
            wind_kph: 1.4,
            wind_degree: 134,
            wind_dir: "SE",
            pressure_mb: 1017,
            pressure_in: 30.03,
            precip_mm: 0,
            precip_in: 0,
            humidity: 94,
            cloud: 81,
            feelslike_c: 16.4,
            feelslike_f: 61.6,
            windchill_c: 16.4,
            windchill_f: 61.6,
            heatindex_c: 16.4,
            heatindex_f: 61.6,
            dewpoint_c: 15.4,
            dewpoint_f: 59.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 1.6,
            gust_kph: 2.6,
            uv: 1,
          },
          {
            time_epoch: 1700982000,
            time: "2023-11-26 04:00",
            temp_c: 16.4,
            temp_f: 61.6,
            is_day: 0,
            condition: {
              text: "Parcialmente nublado",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 1.3,
            wind_kph: 2.2,
            wind_degree: 138,
            wind_dir: "SE",
            pressure_mb: 1017,
            pressure_in: 30.03,
            precip_mm: 0,
            precip_in: 0,
            humidity: 94,
            cloud: 58,
            feelslike_c: 16.4,
            feelslike_f: 61.6,
            windchill_c: 16.4,
            windchill_f: 61.6,
            heatindex_c: 16.4,
            heatindex_f: 61.6,
            dewpoint_c: 15.4,
            dewpoint_f: 59.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 2.4,
            gust_kph: 3.9,
            uv: 1,
          },
          {
            time_epoch: 1700985600,
            time: "2023-11-26 05:00",
            temp_c: 16.4,
            temp_f: 61.6,
            is_day: 0,
            condition: {
              text: "Nublado",
              icon: "//cdn.weatherapi.com/weather/64x64/night/119.png",
              code: 1006,
            },
            wind_mph: 1.8,
            wind_kph: 2.9,
            wind_degree: 117,
            wind_dir: "ESE",
            pressure_mb: 1017,
            pressure_in: 30.03,
            precip_mm: 0,
            precip_in: 0,
            humidity: 94,
            cloud: 74,
            feelslike_c: 16.4,
            feelslike_f: 61.6,
            windchill_c: 16.4,
            windchill_f: 61.6,
            heatindex_c: 16.4,
            heatindex_f: 61.6,
            dewpoint_c: 15.4,
            dewpoint_f: 59.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.2,
            gust_kph: 5.1,
            uv: 1,
          },
          {
            time_epoch: 1700989200,
            time: "2023-11-26 06:00",
            temp_c: 16.1,
            temp_f: 60.9,
            is_day: 1,
            condition: {
              text: "Neblina",
              icon: "//cdn.weatherapi.com/weather/64x64/day/143.png",
              code: 1030,
            },
            wind_mph: 2,
            wind_kph: 3.2,
            wind_degree: 94,
            wind_dir: "E",
            pressure_mb: 1018,
            pressure_in: 30.05,
            precip_mm: 0,
            precip_in: 0,
            humidity: 95,
            cloud: 97,
            feelslike_c: 16.1,
            feelslike_f: 60.9,
            windchill_c: 16.1,
            windchill_f: 60.9,
            heatindex_c: 16.1,
            heatindex_f: 60.9,
            dewpoint_c: 15.2,
            dewpoint_f: 59.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2,
            vis_miles: 1,
            gust_mph: 3.7,
            gust_kph: 5.9,
            uv: 4,
          },
          {
            time_epoch: 1700992800,
            time: "2023-11-26 07:00",
            temp_c: 16.9,
            temp_f: 62.4,
            is_day: 1,
            condition: {
              text: "Possibilidade de chuva irregular",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 2,
            wind_kph: 3.2,
            wind_degree: 108,
            wind_dir: "ESE",
            pressure_mb: 1018,
            pressure_in: 30.07,
            precip_mm: 0.01,
            precip_in: 0,
            humidity: 92,
            cloud: 100,
            feelslike_c: 16.9,
            feelslike_f: 62.4,
            windchill_c: 16.9,
            windchill_f: 62.4,
            heatindex_c: 16.9,
            heatindex_f: 62.4,
            dewpoint_c: 15.7,
            dewpoint_f: 60.2,
            will_it_rain: 1,
            chance_of_rain: 83,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.4,
            gust_kph: 5.4,
            uv: 4,
          },
          {
            time_epoch: 1700996400,
            time: "2023-11-26 08:00",
            temp_c: 17.8,
            temp_f: 64,
            is_day: 1,
            condition: {
              text: "Possibilidade de chuva irregular",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 2.7,
            wind_kph: 4.3,
            wind_degree: 101,
            wind_dir: "ESE",
            pressure_mb: 1019,
            pressure_in: 30.08,
            precip_mm: 0.03,
            precip_in: 0,
            humidity: 87,
            cloud: 100,
            feelslike_c: 17.8,
            feelslike_f: 64,
            windchill_c: 17.8,
            windchill_f: 64,
            heatindex_c: 17.8,
            heatindex_f: 64,
            dewpoint_c: 15.6,
            dewpoint_f: 60.1,
            will_it_rain: 0,
            chance_of_rain: 61,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.1,
            gust_kph: 6.6,
            uv: 4,
          },
          {
            time_epoch: 1701000000,
            time: "2023-11-26 09:00",
            temp_c: 18.3,
            temp_f: 65,
            is_day: 1,
            condition: {
              text: "Possibilidade de chuva irregular",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 2.5,
            wind_kph: 4,
            wind_degree: 85,
            wind_dir: "E",
            pressure_mb: 1019,
            pressure_in: 30.09,
            precip_mm: 0.05,
            precip_in: 0,
            humidity: 84,
            cloud: 100,
            feelslike_c: 18.3,
            feelslike_f: 65,
            windchill_c: 18.3,
            windchill_f: 65,
            heatindex_c: 18.3,
            heatindex_f: 65,
            dewpoint_c: 15.7,
            dewpoint_f: 60.2,
            will_it_rain: 1,
            chance_of_rain: 74,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.7,
            gust_kph: 5.9,
            uv: 4,
          },
          {
            time_epoch: 1701003600,
            time: "2023-11-26 10:00",
            temp_c: 18.9,
            temp_f: 66,
            is_day: 1,
            condition: {
              text: "Possibilidade de chuva irregular",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 2.5,
            wind_kph: 4,
            wind_degree: 84,
            wind_dir: "E",
            pressure_mb: 1019,
            pressure_in: 30.09,
            precip_mm: 0.04,
            precip_in: 0,
            humidity: 81,
            cloud: 100,
            feelslike_c: 18.9,
            feelslike_f: 66,
            windchill_c: 18.9,
            windchill_f: 66,
            heatindex_c: 18.9,
            heatindex_f: 66,
            dewpoint_c: 15.6,
            dewpoint_f: 60.2,
            will_it_rain: 1,
            chance_of_rain: 74,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.6,
            gust_kph: 5.9,
            uv: 4,
          },
          {
            time_epoch: 1701007200,
            time: "2023-11-26 11:00",
            temp_c: 19.4,
            temp_f: 66.9,
            is_day: 1,
            condition: {
              text: "Possibilidade de chuva irregular",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 2.7,
            wind_kph: 4.3,
            wind_degree: 89,
            wind_dir: "E",
            pressure_mb: 1019,
            pressure_in: 30.08,
            precip_mm: 0.04,
            precip_in: 0,
            humidity: 79,
            cloud: 100,
            feelslike_c: 19.4,
            feelslike_f: 66.9,
            windchill_c: 19.4,
            windchill_f: 66.9,
            heatindex_c: 19.4,
            heatindex_f: 66.9,
            dewpoint_c: 15.6,
            dewpoint_f: 60.1,
            will_it_rain: 0,
            chance_of_rain: 62,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.9,
            gust_kph: 6.3,
            uv: 4,
          },
          {
            time_epoch: 1701010800,
            time: "2023-11-26 12:00",
            temp_c: 19.9,
            temp_f: 67.8,
            is_day: 1,
            condition: {
              text: "Possibilidade de chuva irregular",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 3.4,
            wind_kph: 5.4,
            wind_degree: 76,
            wind_dir: "ENE",
            pressure_mb: 1018,
            pressure_in: 30.07,
            precip_mm: 0.02,
            precip_in: 0,
            humidity: 77,
            cloud: 100,
            feelslike_c: 19.9,
            feelslike_f: 67.8,
            windchill_c: 19.9,
            windchill_f: 67.8,
            heatindex_c: 19.9,
            heatindex_f: 67.8,
            dewpoint_c: 15.6,
            dewpoint_f: 60.1,
            will_it_rain: 1,
            chance_of_rain: 77,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.9,
            gust_kph: 7.8,
            uv: 4,
          },
          {
            time_epoch: 1701014400,
            time: "2023-11-26 13:00",
            temp_c: 21.2,
            temp_f: 70.1,
            is_day: 1,
            condition: {
              text: "Possibilidade de chuva irregular",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 3.4,
            wind_kph: 5.4,
            wind_degree: 75,
            wind_dir: "ENE",
            pressure_mb: 1017,
            pressure_in: 30.04,
            precip_mm: 0.01,
            precip_in: 0,
            humidity: 72,
            cloud: 100,
            feelslike_c: 21.2,
            feelslike_f: 70.1,
            windchill_c: 21.2,
            windchill_f: 70.1,
            heatindex_c: 24.4,
            heatindex_f: 75.9,
            dewpoint_c: 15.9,
            dewpoint_f: 60.6,
            will_it_rain: 1,
            chance_of_rain: 78,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.7,
            gust_kph: 7.6,
            uv: 5,
          },
          {
            time_epoch: 1701018000,
            time: "2023-11-26 14:00",
            temp_c: 22.5,
            temp_f: 72.5,
            is_day: 1,
            condition: {
              text: "Possibilidade de chuva irregular",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 3.1,
            wind_kph: 5,
            wind_degree: 73,
            wind_dir: "ENE",
            pressure_mb: 1017,
            pressure_in: 30.02,
            precip_mm: 0.02,
            precip_in: 0,
            humidity: 67,
            cloud: 92,
            feelslike_c: 24.7,
            feelslike_f: 76.5,
            windchill_c: 22.5,
            windchill_f: 72.5,
            heatindex_c: 24.7,
            heatindex_f: 76.5,
            dewpoint_c: 16.1,
            dewpoint_f: 61,
            will_it_rain: 1,
            chance_of_rain: 74,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.1,
            gust_kph: 6.6,
            uv: 5,
          },
          {
            time_epoch: 1701021600,
            time: "2023-11-26 15:00",
            temp_c: 22.8,
            temp_f: 73.1,
            is_day: 1,
            condition: {
              text: "Possibilidade de chuva irregular",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 3.1,
            wind_kph: 5,
            wind_degree: 78,
            wind_dir: "ENE",
            pressure_mb: 1016,
            pressure_in: 30,
            precip_mm: 0.01,
            precip_in: 0,
            humidity: 65,
            cloud: 75,
            feelslike_c: 24.9,
            feelslike_f: 76.8,
            windchill_c: 22.9,
            windchill_f: 73.1,
            heatindex_c: 24.9,
            heatindex_f: 76.8,
            dewpoint_c: 15.9,
            dewpoint_f: 60.6,
            will_it_rain: 0,
            chance_of_rain: 60,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.3,
            gust_kph: 6.9,
            uv: 5,
          },
          {
            time_epoch: 1701025200,
            time: "2023-11-26 16:00",
            temp_c: 22.3,
            temp_f: 72.2,
            is_day: 1,
            condition: {
              text: "Nublado",
              icon: "//cdn.weatherapi.com/weather/64x64/day/119.png",
              code: 1006,
            },
            wind_mph: 3.6,
            wind_kph: 5.8,
            wind_degree: 85,
            wind_dir: "E",
            pressure_mb: 1016,
            pressure_in: 29.99,
            precip_mm: 0,
            precip_in: 0,
            humidity: 68,
            cloud: 64,
            feelslike_c: 24.7,
            feelslike_f: 76.4,
            windchill_c: 22.3,
            windchill_f: 72.2,
            heatindex_c: 24.7,
            heatindex_f: 76.4,
            dewpoint_c: 16.1,
            dewpoint_f: 61.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.5,
            gust_kph: 8.8,
            uv: 5,
          },
          {
            time_epoch: 1701028800,
            time: "2023-11-26 17:00",
            temp_c: 22.1,
            temp_f: 71.7,
            is_day: 1,
            condition: {
              text: "Parcialmente nublado",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 4,
            wind_kph: 6.5,
            wind_degree: 85,
            wind_dir: "E",
            pressure_mb: 1015,
            pressure_in: 29.99,
            precip_mm: 0,
            precip_in: 0,
            humidity: 70,
            cloud: 59,
            feelslike_c: 24.6,
            feelslike_f: 76.3,
            windchill_c: 22.1,
            windchill_f: 71.7,
            heatindex_c: 24.6,
            heatindex_f: 76.3,
            dewpoint_c: 16.3,
            dewpoint_f: 61.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.3,
            gust_kph: 10.2,
            uv: 6,
          },
          {
            time_epoch: 1701032400,
            time: "2023-11-26 18:00",
            temp_c: 21.8,
            temp_f: 71.2,
            is_day: 1,
            condition: {
              text: "Encoberto",
              icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
              code: 1009,
            },
            wind_mph: 3.6,
            wind_kph: 5.8,
            wind_degree: 89,
            wind_dir: "E",
            pressure_mb: 1016,
            pressure_in: 29.99,
            precip_mm: 0,
            precip_in: 0,
            humidity: 73,
            cloud: 100,
            feelslike_c: 21.8,
            feelslike_f: 71.2,
            windchill_c: 21.8,
            windchill_f: 71.2,
            heatindex_c: 24.5,
            heatindex_f: 76.1,
            dewpoint_c: 16.7,
            dewpoint_f: 62.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.7,
            gust_kph: 9.1,
            uv: 5,
          },
          {
            time_epoch: 1701036000,
            time: "2023-11-26 19:00",
            temp_c: 22.2,
            temp_f: 71.9,
            is_day: 0,
            condition: {
              text: "Nublado",
              icon: "//cdn.weatherapi.com/weather/64x64/night/119.png",
              code: 1006,
            },
            wind_mph: 2.9,
            wind_kph: 4.7,
            wind_degree: 90,
            wind_dir: "E",
            pressure_mb: 1016,
            pressure_in: 30,
            precip_mm: 0,
            precip_in: 0,
            humidity: 79,
            cloud: 83,
            feelslike_c: 24.6,
            feelslike_f: 76.3,
            windchill_c: 22.2,
            windchill_f: 71.9,
            heatindex_c: 24.6,
            heatindex_f: 76.3,
            dewpoint_c: 18.3,
            dewpoint_f: 65,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4,
            gust_kph: 6.5,
            uv: 1,
          },
          {
            time_epoch: 1701039600,
            time: "2023-11-26 20:00",
            temp_c: 21,
            temp_f: 69.9,
            is_day: 0,
            condition: {
              text: "Encoberto",
              icon: "//cdn.weatherapi.com/weather/64x64/night/122.png",
              code: 1009,
            },
            wind_mph: 2.9,
            wind_kph: 4.7,
            wind_degree: 103,
            wind_dir: "ESE",
            pressure_mb: 1017,
            pressure_in: 30.03,
            precip_mm: 0,
            precip_in: 0,
            humidity: 83,
            cloud: 91,
            feelslike_c: 21,
            feelslike_f: 69.9,
            windchill_c: 21,
            windchill_f: 69.9,
            heatindex_c: 24.2,
            heatindex_f: 75.6,
            dewpoint_c: 18.1,
            dewpoint_f: 64.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.6,
            gust_kph: 7.4,
            uv: 1,
          },
          {
            time_epoch: 1701043200,
            time: "2023-11-26 21:00",
            temp_c: 20.3,
            temp_f: 68.6,
            is_day: 0,
            condition: {
              text: "Nublado",
              icon: "//cdn.weatherapi.com/weather/64x64/night/119.png",
              code: 1006,
            },
            wind_mph: 2.2,
            wind_kph: 3.6,
            wind_degree: 125,
            wind_dir: "SE",
            pressure_mb: 1018,
            pressure_in: 30.06,
            precip_mm: 0,
            precip_in: 0,
            humidity: 86,
            cloud: 84,
            feelslike_c: 20.3,
            feelslike_f: 68.6,
            windchill_c: 20.3,
            windchill_f: 68.6,
            heatindex_c: 20.3,
            heatindex_f: 68.6,
            dewpoint_c: 18,
            dewpoint_f: 64.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.6,
            gust_kph: 5.9,
            uv: 1,
          },
          {
            time_epoch: 1701046800,
            time: "2023-11-26 22:00",
            temp_c: 19,
            temp_f: 66.1,
            is_day: 0,
            condition: {
              text: "Nublado",
              icon: "//cdn.weatherapi.com/weather/64x64/night/119.png",
              code: 1006,
            },
            wind_mph: 2.5,
            wind_kph: 4,
            wind_degree: 133,
            wind_dir: "SE",
            pressure_mb: 1018,
            pressure_in: 30.08,
            precip_mm: 0,
            precip_in: 0,
            humidity: 89,
            cloud: 70,
            feelslike_c: 19,
            feelslike_f: 66.1,
            windchill_c: 19,
            windchill_f: 66.1,
            heatindex_c: 19,
            heatindex_f: 66.1,
            dewpoint_c: 17.2,
            dewpoint_f: 62.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.7,
            gust_kph: 7.5,
            uv: 1,
          },
          {
            time_epoch: 1701050400,
            time: "2023-11-26 23:00",
            temp_c: 17.8,
            temp_f: 64,
            is_day: 0,
            condition: {
              text: "Nublado",
              icon: "//cdn.weatherapi.com/weather/64x64/night/119.png",
              code: 1006,
            },
            wind_mph: 2.7,
            wind_kph: 4.3,
            wind_degree: 115,
            wind_dir: "ESE",
            pressure_mb: 1019,
            pressure_in: 30.08,
            precip_mm: 0,
            precip_in: 0,
            humidity: 91,
            cloud: 87,
            feelslike_c: 17.8,
            feelslike_f: 64,
            windchill_c: 17.8,
            windchill_f: 64,
            heatindex_c: 17.8,
            heatindex_f: 64,
            dewpoint_c: 16.3,
            dewpoint_f: 61.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.6,
            gust_kph: 9.1,
            uv: 1,
          },
        ],
      },
      {
        date: "2023-11-27",
        date_epoch: 1701043200,
        day: {
          maxtemp_c: 28.4,
          maxtemp_f: 83.1,
          mintemp_c: 15.1,
          mintemp_f: 59.2,
          avgtemp_c: 21.2,
          avgtemp_f: 70.1,
          maxwind_mph: 4.9,
          maxwind_kph: 7.9,
          totalprecip_mm: 0.32,
          totalprecip_in: 0.01,
          totalsnow_cm: 0,
          avgvis_km: 7.4,
          avgvis_miles: 4,
          avghumidity: 76,
          daily_will_it_rain: 1,
          daily_chance_of_rain: 82,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Possibilidade de chuva irregular",
            icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
            code: 1063,
          },
          uv: 5,
        },
        astro: {
          sunrise: "05:04 AM",
          sunset: "06:16 PM",
          moonrise: "06:46 PM",
          moonset: "04:57 AM",
          moon_phase: "Full Moon",
          moon_illumination: 100,
          is_moon_up: 1,
          is_sun_up: 0,
        },
        hour: [
          {
            time_epoch: 1701054000,
            time: "2023-11-27 00:00",
            temp_c: 16.7,
            temp_f: 62,
            is_day: 0,
            condition: {
              text: "Parcialmente nublado",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 2.2,
            wind_kph: 3.6,
            wind_degree: 99,
            wind_dir: "E",
            pressure_mb: 1018,
            pressure_in: 30.07,
            precip_mm: 0,
            precip_in: 0,
            humidity: 94,
            cloud: 43,
            feelslike_c: 16.7,
            feelslike_f: 62,
            windchill_c: 16.7,
            windchill_f: 62,
            heatindex_c: 16.7,
            heatindex_f: 62,
            dewpoint_c: 15.7,
            dewpoint_f: 60.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.7,
            gust_kph: 7.6,
            uv: 1,
          },
          {
            time_epoch: 1701057600,
            time: "2023-11-27 01:00",
            temp_c: 16.4,
            temp_f: 61.5,
            is_day: 0,
            condition: {
              text: "Neblina",
              icon: "//cdn.weatherapi.com/weather/64x64/night/143.png",
              code: 1030,
            },
            wind_mph: 1.8,
            wind_kph: 2.9,
            wind_degree: 64,
            wind_dir: "ENE",
            pressure_mb: 1018,
            pressure_in: 30.06,
            precip_mm: 0,
            precip_in: 0,
            humidity: 96,
            cloud: 56,
            feelslike_c: 16.4,
            feelslike_f: 61.5,
            windchill_c: 16.4,
            windchill_f: 61.5,
            heatindex_c: 16.4,
            heatindex_f: 61.5,
            dewpoint_c: 15.7,
            dewpoint_f: 60.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2,
            vis_miles: 1,
            gust_mph: 3.8,
            gust_kph: 6,
            uv: 1,
          },
          {
            time_epoch: 1701061200,
            time: "2023-11-27 02:00",
            temp_c: 16,
            temp_f: 60.8,
            is_day: 0,
            condition: {
              text: "Neblina",
              icon: "//cdn.weatherapi.com/weather/64x64/night/143.png",
              code: 1030,
            },
            wind_mph: 1.3,
            wind_kph: 2.2,
            wind_degree: 44,
            wind_dir: "NE",
            pressure_mb: 1017,
            pressure_in: 30.04,
            precip_mm: 0,
            precip_in: 0,
            humidity: 97,
            cloud: 54,
            feelslike_c: 16,
            feelslike_f: 60.8,
            windchill_c: 16,
            windchill_f: 60.8,
            heatindex_c: 16,
            heatindex_f: 60.8,
            dewpoint_c: 15.5,
            dewpoint_f: 59.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2,
            vis_miles: 1,
            gust_mph: 2.8,
            gust_kph: 4.5,
            uv: 1,
          },
          {
            time_epoch: 1701064800,
            time: "2023-11-27 03:00",
            temp_c: 15.7,
            temp_f: 60.2,
            is_day: 0,
            condition: {
              text: "Nevoeiro",
              icon: "//cdn.weatherapi.com/weather/64x64/night/248.png",
              code: 1135,
            },
            wind_mph: 0.9,
            wind_kph: 1.4,
            wind_degree: 57,
            wind_dir: "ENE",
            pressure_mb: 1017,
            pressure_in: 30.03,
            precip_mm: 0,
            precip_in: 0,
            humidity: 97,
            cloud: 100,
            feelslike_c: 15.7,
            feelslike_f: 60.2,
            windchill_c: 15.7,
            windchill_f: 60.2,
            heatindex_c: 15.7,
            heatindex_f: 60.2,
            dewpoint_c: 15.2,
            dewpoint_f: 59.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 0,
            vis_miles: 0,
            gust_mph: 1.9,
            gust_kph: 3,
            uv: 1,
          },
          {
            time_epoch: 1701068400,
            time: "2023-11-27 04:00",
            temp_c: 15.4,
            temp_f: 59.7,
            is_day: 0,
            condition: {
              text: "Nevoeiro",
              icon: "//cdn.weatherapi.com/weather/64x64/night/248.png",
              code: 1135,
            },
            wind_mph: 1.3,
            wind_kph: 2.2,
            wind_degree: 69,
            wind_dir: "ENE",
            pressure_mb: 1017,
            pressure_in: 30.04,
            precip_mm: 0,
            precip_in: 0,
            humidity: 98,
            cloud: 100,
            feelslike_c: 15.4,
            feelslike_f: 59.7,
            windchill_c: 15.4,
            windchill_f: 59.7,
            heatindex_c: 15.4,
            heatindex_f: 59.7,
            dewpoint_c: 15,
            dewpoint_f: 59.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 0,
            vis_miles: 0,
            gust_mph: 2.8,
            gust_kph: 4.5,
            uv: 1,
          },
          {
            time_epoch: 1701072000,
            time: "2023-11-27 05:00",
            temp_c: 15.1,
            temp_f: 59.2,
            is_day: 0,
            condition: {
              text: "Nevoeiro",
              icon: "//cdn.weatherapi.com/weather/64x64/night/248.png",
              code: 1135,
            },
            wind_mph: 0.7,
            wind_kph: 1.1,
            wind_degree: 57,
            wind_dir: "ENE",
            pressure_mb: 1018,
            pressure_in: 30.06,
            precip_mm: 0,
            precip_in: 0,
            humidity: 98,
            cloud: 100,
            feelslike_c: 15.1,
            feelslike_f: 59.2,
            windchill_c: 15.1,
            windchill_f: 59.2,
            heatindex_c: 15.1,
            heatindex_f: 59.2,
            dewpoint_c: 14.8,
            dewpoint_f: 58.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 0,
            vis_miles: 0,
            gust_mph: 1.4,
            gust_kph: 2.3,
            uv: 1,
          },
          {
            time_epoch: 1701075600,
            time: "2023-11-27 06:00",
            temp_c: 15,
            temp_f: 58.9,
            is_day: 1,
            condition: {
              text: "Nevoeiro",
              icon: "//cdn.weatherapi.com/weather/64x64/day/248.png",
              code: 1135,
            },
            wind_mph: 1.3,
            wind_kph: 2.2,
            wind_degree: 48,
            wind_dir: "NE",
            pressure_mb: 1019,
            pressure_in: 30.08,
            precip_mm: 0,
            precip_in: 0,
            humidity: 98,
            cloud: 100,
            feelslike_c: 15,
            feelslike_f: 58.9,
            windchill_c: 15,
            windchill_f: 58.9,
            heatindex_c: 15,
            heatindex_f: 58.9,
            dewpoint_c: 14.7,
            dewpoint_f: 58.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 0,
            vis_miles: 0,
            gust_mph: 2.8,
            gust_kph: 4.5,
            uv: 3,
          },
          {
            time_epoch: 1701079200,
            time: "2023-11-27 07:00",
            temp_c: 16.3,
            temp_f: 61.3,
            is_day: 1,
            condition: {
              text: "Encoberto",
              icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
              code: 1009,
            },
            wind_mph: 1.3,
            wind_kph: 2.2,
            wind_degree: 44,
            wind_dir: "NE",
            pressure_mb: 1019,
            pressure_in: 30.1,
            precip_mm: 0,
            precip_in: 0,
            humidity: 93,
            cloud: 94,
            feelslike_c: 16.3,
            feelslike_f: 61.3,
            windchill_c: 16.3,
            windchill_f: 61.3,
            heatindex_c: 16.3,
            heatindex_f: 61.3,
            dewpoint_c: 15.1,
            dewpoint_f: 59.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 2.4,
            gust_kph: 3.9,
            uv: 4,
          },
          {
            time_epoch: 1701082800,
            time: "2023-11-27 08:00",
            temp_c: 18.9,
            temp_f: 66.1,
            is_day: 1,
            condition: {
              text: "Nublado",
              icon: "//cdn.weatherapi.com/weather/64x64/day/119.png",
              code: 1006,
            },
            wind_mph: 2.5,
            wind_kph: 4,
            wind_degree: 36,
            wind_dir: "NE",
            pressure_mb: 1019,
            pressure_in: 30.1,
            precip_mm: 0,
            precip_in: 0,
            humidity: 80,
            cloud: 82,
            feelslike_c: 18.9,
            feelslike_f: 66.1,
            windchill_c: 18.9,
            windchill_f: 66.1,
            heatindex_c: 18.9,
            heatindex_f: 66.1,
            dewpoint_c: 15.4,
            dewpoint_f: 59.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.3,
            gust_kph: 5.3,
            uv: 4,
          },
          {
            time_epoch: 1701086400,
            time: "2023-11-27 09:00",
            temp_c: 21,
            temp_f: 69.8,
            is_day: 1,
            condition: {
              text: "Possibilidade de chuva irregular",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 3.8,
            wind_kph: 6.1,
            wind_degree: 34,
            wind_dir: "NE",
            pressure_mb: 1019,
            pressure_in: 30.1,
            precip_mm: 0.01,
            precip_in: 0,
            humidity: 71,
            cloud: 100,
            feelslike_c: 21,
            feelslike_f: 69.9,
            windchill_c: 21,
            windchill_f: 69.9,
            heatindex_c: 24.4,
            heatindex_f: 75.9,
            dewpoint_c: 15.6,
            dewpoint_f: 60,
            will_it_rain: 1,
            chance_of_rain: 72,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.6,
            gust_kph: 7.4,
            uv: 5,
          },
          {
            time_epoch: 1701090000,
            time: "2023-11-27 10:00",
            temp_c: 22,
            temp_f: 71.6,
            is_day: 1,
            condition: {
              text: "Possibilidade de chuva irregular",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 4.9,
            wind_kph: 7.9,
            wind_degree: 27,
            wind_dir: "NNE",
            pressure_mb: 1019,
            pressure_in: 30.1,
            precip_mm: 0.02,
            precip_in: 0,
            humidity: 67,
            cloud: 100,
            feelslike_c: 22,
            feelslike_f: 71.6,
            windchill_c: 22,
            windchill_f: 71.6,
            heatindex_c: 24.6,
            heatindex_f: 76.2,
            dewpoint_c: 15.5,
            dewpoint_f: 60,
            will_it_rain: 1,
            chance_of_rain: 89,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6,
            gust_kph: 9.7,
            uv: 5,
          },
          {
            time_epoch: 1701093600,
            time: "2023-11-27 11:00",
            temp_c: 22.3,
            temp_f: 72.2,
            is_day: 1,
            condition: {
              text: "Possibilidade de chuva irregular",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 5.4,
            wind_kph: 8.6,
            wind_degree: 27,
            wind_dir: "NNE",
            pressure_mb: 1019,
            pressure_in: 30.09,
            precip_mm: 0.01,
            precip_in: 0,
            humidity: 66,
            cloud: 81,
            feelslike_c: 24.7,
            feelslike_f: 76.4,
            windchill_c: 22.3,
            windchill_f: 72.2,
            heatindex_c: 24.7,
            heatindex_f: 76.4,
            dewpoint_c: 15.7,
            dewpoint_f: 60.2,
            will_it_rain: 0,
            chance_of_rain: 65,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.8,
            gust_kph: 10.9,
            uv: 5,
          },
          {
            time_epoch: 1701097200,
            time: "2023-11-27 12:00",
            temp_c: 24.2,
            temp_f: 75.6,
            is_day: 1,
            condition: {
              text: "Parcialmente nublado",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 5.1,
            wind_kph: 8.3,
            wind_degree: 30,
            wind_dir: "NNE",
            pressure_mb: 1018,
            pressure_in: 30.07,
            precip_mm: 0,
            precip_in: 0,
            humidity: 59,
            cloud: 35,
            feelslike_c: 25.6,
            feelslike_f: 78.1,
            windchill_c: 24.3,
            windchill_f: 75.7,
            heatindex_c: 25.6,
            heatindex_f: 78.1,
            dewpoint_c: 15.7,
            dewpoint_f: 60.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.9,
            gust_kph: 9.5,
            uv: 6,
          },
          {
            time_epoch: 1701100800,
            time: "2023-11-27 13:00",
            temp_c: 26.3,
            temp_f: 79.3,
            is_day: 1,
            condition: {
              text: "Parcialmente nublado",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 4.9,
            wind_kph: 7.9,
            wind_degree: 37,
            wind_dir: "NE",
            pressure_mb: 1017,
            pressure_in: 30.03,
            precip_mm: 0,
            precip_in: 0,
            humidity: 52,
            cloud: 48,
            feelslike_c: 27,
            feelslike_f: 80.6,
            windchill_c: 26.3,
            windchill_f: 79.3,
            heatindex_c: 27,
            heatindex_f: 80.6,
            dewpoint_c: 15.7,
            dewpoint_f: 60.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.7,
            gust_kph: 9.1,
            uv: 7,
          },
          {
            time_epoch: 1701104400,
            time: "2023-11-27 14:00",
            temp_c: 27.4,
            temp_f: 81.3,
            is_day: 1,
            condition: {
              text: "Parcialmente nublado",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 4.9,
            wind_kph: 7.9,
            wind_degree: 42,
            wind_dir: "NE",
            pressure_mb: 1016,
            pressure_in: 30,
            precip_mm: 0,
            precip_in: 0,
            humidity: 49,
            cloud: 54,
            feelslike_c: 28,
            feelslike_f: 82.3,
            windchill_c: 27.4,
            windchill_f: 81.3,
            heatindex_c: 28,
            heatindex_f: 82.3,
            dewpoint_c: 15.7,
            dewpoint_f: 60.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.7,
            gust_kph: 9.1,
            uv: 7,
          },
          {
            time_epoch: 1701108000,
            time: "2023-11-27 15:00",
            temp_c: 27.7,
            temp_f: 81.9,
            is_day: 1,
            condition: {
              text: "Parcialmente nublado",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 4.9,
            wind_kph: 7.9,
            wind_degree: 50,
            wind_dir: "NE",
            pressure_mb: 1015,
            pressure_in: 29.97,
            precip_mm: 0,
            precip_in: 0,
            humidity: 48,
            cloud: 47,
            feelslike_c: 28.2,
            feelslike_f: 82.8,
            windchill_c: 27.7,
            windchill_f: 81.9,
            heatindex_c: 28.2,
            heatindex_f: 82.8,
            dewpoint_c: 15.7,
            dewpoint_f: 60.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.7,
            gust_kph: 9.1,
            uv: 7,
          },
          {
            time_epoch: 1701111600,
            time: "2023-11-27 16:00",
            temp_c: 27.6,
            temp_f: 81.7,
            is_day: 1,
            condition: {
              text: "Parcialmente nublado",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 5.1,
            wind_kph: 8.3,
            wind_degree: 63,
            wind_dir: "ENE",
            pressure_mb: 1014,
            pressure_in: 29.96,
            precip_mm: 0,
            precip_in: 0,
            humidity: 48,
            cloud: 31,
            feelslike_c: 28.2,
            feelslike_f: 82.7,
            windchill_c: 27.6,
            windchill_f: 81.7,
            heatindex_c: 28.2,
            heatindex_f: 82.7,
            dewpoint_c: 15.8,
            dewpoint_f: 60.4,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.6,
            gust_kph: 10.7,
            uv: 7,
          },
          {
            time_epoch: 1701115200,
            time: "2023-11-27 17:00",
            temp_c: 26.9,
            temp_f: 80.4,
            is_day: 1,
            condition: {
              text: "Parcialmente nublado",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 5.1,
            wind_kph: 8.3,
            wind_degree: 78,
            wind_dir: "ENE",
            pressure_mb: 1014,
            pressure_in: 29.95,
            precip_mm: 0,
            precip_in: 0,
            humidity: 52,
            cloud: 29,
            feelslike_c: 27.6,
            feelslike_f: 81.7,
            windchill_c: 26.9,
            windchill_f: 80.4,
            heatindex_c: 27.6,
            heatindex_f: 81.7,
            dewpoint_c: 16.2,
            dewpoint_f: 61.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 7.5,
            gust_kph: 12.1,
            uv: 7,
          },
          {
            time_epoch: 1701118800,
            time: "2023-11-27 18:00",
            temp_c: 25.3,
            temp_f: 77.6,
            is_day: 1,
            condition: {
              text: "Possibilidade de chuva irregular",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 5.6,
            wind_kph: 9,
            wind_degree: 89,
            wind_dir: "E",
            pressure_mb: 1015,
            pressure_in: 29.96,
            precip_mm: 0.04,
            precip_in: 0,
            humidity: 62,
            cloud: 80,
            feelslike_c: 26.6,
            feelslike_f: 79.8,
            windchill_c: 25.3,
            windchill_f: 77.6,
            heatindex_c: 26.6,
            heatindex_f: 79.8,
            dewpoint_c: 17.4,
            dewpoint_f: 63.4,
            will_it_rain: 0,
            chance_of_rain: 60,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 9.2,
            gust_kph: 14.8,
            uv: 6,
          },
          {
            time_epoch: 1701122400,
            time: "2023-11-27 19:00",
            temp_c: 24.1,
            temp_f: 75.4,
            is_day: 0,
            condition: {
              text: "Parcialmente nublado",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 5.6,
            wind_kph: 9,
            wind_degree: 89,
            wind_dir: "E",
            pressure_mb: 1015,
            pressure_in: 29.98,
            precip_mm: 0,
            precip_in: 0,
            humidity: 71,
            cloud: 31,
            feelslike_c: 25.8,
            feelslike_f: 78.4,
            windchill_c: 24.1,
            windchill_f: 75.4,
            heatindex_c: 25.8,
            heatindex_f: 78.4,
            dewpoint_c: 18.4,
            dewpoint_f: 65.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 8.7,
            gust_kph: 13.9,
            uv: 1,
          },
          {
            time_epoch: 1701126000,
            time: "2023-11-27 20:00",
            temp_c: 21.7,
            temp_f: 71.1,
            is_day: 0,
            condition: {
              text: "Possibilidade de chuva irregular",
              icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
              code: 1063,
            },
            wind_mph: 3.8,
            wind_kph: 6.1,
            wind_degree: 88,
            wind_dir: "E",
            pressure_mb: 1016,
            pressure_in: 30,
            precip_mm: 0.04,
            precip_in: 0,
            humidity: 84,
            cloud: 85,
            feelslike_c: 21.7,
            feelslike_f: 71.1,
            windchill_c: 21.7,
            windchill_f: 71.1,
            heatindex_c: 24.4,
            heatindex_f: 75.9,
            dewpoint_c: 18.9,
            dewpoint_f: 66,
            will_it_rain: 1,
            chance_of_rain: 80,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 6.8,
            gust_kph: 11,
            uv: 1,
          },
          {
            time_epoch: 1701129600,
            time: "2023-11-27 21:00",
            temp_c: 20.5,
            temp_f: 68.9,
            is_day: 0,
            condition: {
              text: "Possibilidade de chuva irregular",
              icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
              code: 1063,
            },
            wind_mph: 2,
            wind_kph: 3.2,
            wind_degree: 95,
            wind_dir: "E",
            pressure_mb: 1017,
            pressure_in: 30.02,
            precip_mm: 0.43,
            precip_in: 0.02,
            humidity: 90,
            cloud: 88,
            feelslike_c: 20.5,
            feelslike_f: 68.9,
            windchill_c: 20.5,
            windchill_f: 68.9,
            heatindex_c: 20.5,
            heatindex_f: 68.9,
            dewpoint_c: 18.8,
            dewpoint_f: 65.8,
            will_it_rain: 1,
            chance_of_rain: 88,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9,
            vis_miles: 5,
            gust_mph: 4,
            gust_kph: 6.4,
            uv: 1,
          },
          {
            time_epoch: 1701133200,
            time: "2023-11-27 22:00",
            temp_c: 19.9,
            temp_f: 67.9,
            is_day: 0,
            condition: {
              text: "Céu limpo",
              icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
              code: 1000,
            },
            wind_mph: 1.1,
            wind_kph: 1.8,
            wind_degree: 110,
            wind_dir: "ESE",
            pressure_mb: 1017,
            pressure_in: 30.04,
            precip_mm: 0,
            precip_in: 0,
            humidity: 93,
            cloud: 21,
            feelslike_c: 19.9,
            feelslike_f: 67.9,
            windchill_c: 19.9,
            windchill_f: 67.9,
            heatindex_c: 19.9,
            heatindex_f: 67.9,
            dewpoint_c: 18.7,
            dewpoint_f: 65.7,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 2.2,
            gust_kph: 3.6,
            uv: 1,
          },
          {
            time_epoch: 1701136800,
            time: "2023-11-27 23:00",
            temp_c: 19.6,
            temp_f: 67.3,
            is_day: 0,
            condition: {
              text: "Neblina",
              icon: "//cdn.weatherapi.com/weather/64x64/night/143.png",
              code: 1030,
            },
            wind_mph: 1.3,
            wind_kph: 2.2,
            wind_degree: 99,
            wind_dir: "E",
            pressure_mb: 1018,
            pressure_in: 30.06,
            precip_mm: 0,
            precip_in: 0,
            humidity: 94,
            cloud: 29,
            feelslike_c: 19.6,
            feelslike_f: 67.2,
            windchill_c: 19.6,
            windchill_f: 67.2,
            heatindex_c: 19.6,
            heatindex_f: 67.2,
            dewpoint_c: 18.6,
            dewpoint_f: 65.5,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2,
            vis_miles: 1,
            gust_mph: 2.6,
            gust_kph: 4.2,
            uv: 1,
          },
        ],
      },
      {
        date: "2023-11-28",
        date_epoch: 1701129600,
        day: {
          maxtemp_c: 26.9,
          maxtemp_f: 80.5,
          mintemp_c: 16.7,
          mintemp_f: 62,
          avgtemp_c: 21.5,
          avgtemp_f: 70.6,
          maxwind_mph: 5.1,
          maxwind_kph: 8.3,
          totalprecip_mm: 10.53,
          totalprecip_in: 0.41,
          totalsnow_cm: 0,
          avgvis_km: 7.3,
          avgvis_miles: 4,
          avghumidity: 82,
          daily_will_it_rain: 1,
          daily_chance_of_rain: 76,
          daily_will_it_snow: 0,
          daily_chance_of_snow: 0,
          condition: {
            text: "Chuva moderada",
            icon: "//cdn.weatherapi.com/weather/64x64/day/302.png",
            code: 1189,
          },
          uv: 5,
        },
        astro: {
          sunrise: "05:04 AM",
          sunset: "06:17 PM",
          moonrise: "07:47 PM",
          moonset: "05:48 AM",
          moon_phase: "Waning Gibbous",
          moon_illumination: 99,
          is_moon_up: 1,
          is_sun_up: 0,
        },
        hour: [
          {
            time_epoch: 1701140400,
            time: "2023-11-28 00:00",
            temp_c: 19.3,
            temp_f: 66.7,
            is_day: 0,
            condition: {
              text: "Neblina",
              icon: "//cdn.weatherapi.com/weather/64x64/night/143.png",
              code: 1030,
            },
            wind_mph: 1.3,
            wind_kph: 2.2,
            wind_degree: 64,
            wind_dir: "ENE",
            pressure_mb: 1018,
            pressure_in: 30.06,
            precip_mm: 0,
            precip_in: 0,
            humidity: 95,
            cloud: 40,
            feelslike_c: 19.3,
            feelslike_f: 66.7,
            windchill_c: 19.3,
            windchill_f: 66.7,
            heatindex_c: 19.3,
            heatindex_f: 66.7,
            dewpoint_c: 18.5,
            dewpoint_f: 65.3,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2,
            vis_miles: 1,
            gust_mph: 2.6,
            gust_kph: 4.1,
            uv: 1,
          },
          {
            time_epoch: 1701144000,
            time: "2023-11-28 01:00",
            temp_c: 19,
            temp_f: 66.2,
            is_day: 0,
            condition: {
              text: "Neblina",
              icon: "//cdn.weatherapi.com/weather/64x64/night/143.png",
              code: 1030,
            },
            wind_mph: 1.6,
            wind_kph: 2.5,
            wind_degree: 26,
            wind_dir: "NNE",
            pressure_mb: 1018,
            pressure_in: 30.05,
            precip_mm: 0,
            precip_in: 0,
            humidity: 96,
            cloud: 53,
            feelslike_c: 19,
            feelslike_f: 66.2,
            windchill_c: 19,
            windchill_f: 66.2,
            heatindex_c: 19,
            heatindex_f: 66.2,
            dewpoint_c: 18.4,
            dewpoint_f: 65.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 2,
            vis_miles: 1,
            gust_mph: 2.8,
            gust_kph: 4.5,
            uv: 1,
          },
          {
            time_epoch: 1701147600,
            time: "2023-11-28 02:00",
            temp_c: 18.7,
            temp_f: 65.7,
            is_day: 0,
            condition: {
              text: "Nevoeiro",
              icon: "//cdn.weatherapi.com/weather/64x64/night/248.png",
              code: 1135,
            },
            wind_mph: 2.7,
            wind_kph: 4.3,
            wind_degree: 13,
            wind_dir: "NNE",
            pressure_mb: 1017,
            pressure_in: 30.03,
            precip_mm: 0,
            precip_in: 0,
            humidity: 98,
            cloud: 100,
            feelslike_c: 18.7,
            feelslike_f: 65.7,
            windchill_c: 18.7,
            windchill_f: 65.7,
            heatindex_c: 18.7,
            heatindex_f: 65.7,
            dewpoint_c: 18.3,
            dewpoint_f: 65,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 0,
            vis_miles: 0,
            gust_mph: 4.6,
            gust_kph: 7.4,
            uv: 1,
          },
          {
            time_epoch: 1701151200,
            time: "2023-11-28 03:00",
            temp_c: 18.5,
            temp_f: 65.4,
            is_day: 0,
            condition: {
              text: "Nevoeiro",
              icon: "//cdn.weatherapi.com/weather/64x64/night/248.png",
              code: 1135,
            },
            wind_mph: 2.2,
            wind_kph: 3.6,
            wind_degree: 14,
            wind_dir: "NNE",
            pressure_mb: 1016,
            pressure_in: 30.02,
            precip_mm: 0.04,
            precip_in: 0,
            humidity: 98,
            cloud: 100,
            feelslike_c: 18.5,
            feelslike_f: 65.4,
            windchill_c: 18.5,
            windchill_f: 65.4,
            heatindex_c: 18.5,
            heatindex_f: 65.4,
            dewpoint_c: 18.2,
            dewpoint_f: 64.8,
            will_it_rain: 1,
            chance_of_rain: 75,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 0,
            vis_miles: 0,
            gust_mph: 3.6,
            gust_kph: 5.9,
            uv: 1,
          },
          {
            time_epoch: 1701154800,
            time: "2023-11-28 04:00",
            temp_c: 18.4,
            temp_f: 65.2,
            is_day: 0,
            condition: {
              text: "Nevoeiro",
              icon: "//cdn.weatherapi.com/weather/64x64/night/248.png",
              code: 1135,
            },
            wind_mph: 1.6,
            wind_kph: 2.5,
            wind_degree: 34,
            wind_dir: "NE",
            pressure_mb: 1016,
            pressure_in: 30.01,
            precip_mm: 0.12,
            precip_in: 0,
            humidity: 98,
            cloud: 100,
            feelslike_c: 18.4,
            feelslike_f: 65.2,
            windchill_c: 18.4,
            windchill_f: 65.2,
            heatindex_c: 18.4,
            heatindex_f: 65.2,
            dewpoint_c: 18.2,
            dewpoint_f: 64.7,
            will_it_rain: 0,
            chance_of_rain: 65,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 0,
            vis_miles: 0,
            gust_mph: 2.5,
            gust_kph: 4,
            uv: 1,
          },
          {
            time_epoch: 1701158400,
            time: "2023-11-28 05:00",
            temp_c: 17.8,
            temp_f: 64,
            is_day: 0,
            condition: {
              text: "Aguaceiros fracos",
              icon: "//cdn.weatherapi.com/weather/64x64/night/353.png",
              code: 1240,
            },
            wind_mph: 0.9,
            wind_kph: 1.4,
            wind_degree: 23,
            wind_dir: "NNE",
            pressure_mb: 1017,
            pressure_in: 30.03,
            precip_mm: 0.23,
            precip_in: 0.01,
            humidity: 99,
            cloud: 84,
            feelslike_c: 17.8,
            feelslike_f: 64,
            windchill_c: 17.8,
            windchill_f: 64,
            heatindex_c: 17.8,
            heatindex_f: 64,
            dewpoint_c: 17.5,
            dewpoint_f: 63.6,
            will_it_rain: 1,
            chance_of_rain: 80,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 1.5,
            gust_kph: 2.4,
            uv: 1,
          },
          {
            time_epoch: 1701162000,
            time: "2023-11-28 06:00",
            temp_c: 17.4,
            temp_f: 63.3,
            is_day: 1,
            condition: {
              text: "Nevoeiro",
              icon: "//cdn.weatherapi.com/weather/64x64/day/248.png",
              code: 1135,
            },
            wind_mph: 0.9,
            wind_kph: 1.4,
            wind_degree: 21,
            wind_dir: "NNE",
            pressure_mb: 1017,
            pressure_in: 30.04,
            precip_mm: 0.04,
            precip_in: 0,
            humidity: 99,
            cloud: 100,
            feelslike_c: 17.4,
            feelslike_f: 63.3,
            windchill_c: 17.4,
            windchill_f: 63.3,
            heatindex_c: 17.4,
            heatindex_f: 63.3,
            dewpoint_c: 17.2,
            dewpoint_f: 62.9,
            will_it_rain: 1,
            chance_of_rain: 77,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 0,
            vis_miles: 0,
            gust_mph: 1.6,
            gust_kph: 2.6,
            uv: 4,
          },
          {
            time_epoch: 1701165600,
            time: "2023-11-28 07:00",
            temp_c: 17.4,
            temp_f: 63.3,
            is_day: 1,
            condition: {
              text: "Nublado",
              icon: "//cdn.weatherapi.com/weather/64x64/day/119.png",
              code: 1006,
            },
            wind_mph: 0.2,
            wind_kph: 0.4,
            wind_degree: 77,
            wind_dir: "ENE",
            pressure_mb: 1018,
            pressure_in: 30.07,
            precip_mm: 0,
            precip_in: 0,
            humidity: 96,
            cloud: 83,
            feelslike_c: 17.4,
            feelslike_f: 63.3,
            windchill_c: 17.4,
            windchill_f: 63.3,
            heatindex_c: 17.4,
            heatindex_f: 63.3,
            dewpoint_c: 16.7,
            dewpoint_f: 62.1,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 0.4,
            gust_kph: 0.6,
            uv: 4,
          },
          {
            time_epoch: 1701169200,
            time: "2023-11-28 08:00",
            temp_c: 19,
            temp_f: 66.3,
            is_day: 1,
            condition: {
              text: "Possibilidade de chuva irregular",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 1.1,
            wind_kph: 1.8,
            wind_degree: 20,
            wind_dir: "NNE",
            pressure_mb: 1019,
            pressure_in: 30.08,
            precip_mm: 0.01,
            precip_in: 0,
            humidity: 89,
            cloud: 99,
            feelslike_c: 19,
            feelslike_f: 66.3,
            windchill_c: 19,
            windchill_f: 66.3,
            heatindex_c: 19,
            heatindex_f: 66.3,
            dewpoint_c: 17.3,
            dewpoint_f: 63.1,
            will_it_rain: 0,
            chance_of_rain: 60,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 1.6,
            gust_kph: 2.6,
            uv: 4,
          },
          {
            time_epoch: 1701172800,
            time: "2023-11-28 09:00",
            temp_c: 21.1,
            temp_f: 70,
            is_day: 1,
            condition: {
              text: "Possibilidade de chuva irregular",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 2.5,
            wind_kph: 4,
            wind_degree: 23,
            wind_dir: "NNE",
            pressure_mb: 1018,
            pressure_in: 30.07,
            precip_mm: 0.02,
            precip_in: 0,
            humidity: 79,
            cloud: 96,
            feelslike_c: 21.1,
            feelslike_f: 69.9,
            windchill_c: 21.1,
            windchill_f: 69.9,
            heatindex_c: 24.3,
            heatindex_f: 75.7,
            dewpoint_c: 17.4,
            dewpoint_f: 63.3,
            will_it_rain: 1,
            chance_of_rain: 81,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.1,
            gust_kph: 5,
            uv: 5,
          },
          {
            time_epoch: 1701176400,
            time: "2023-11-28 10:00",
            temp_c: 22.3,
            temp_f: 72.1,
            is_day: 1,
            condition: {
              text: "Possibilidade de chuva irregular",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 3.6,
            wind_kph: 5.8,
            wind_degree: 19,
            wind_dir: "NNE",
            pressure_mb: 1018,
            pressure_in: 30.06,
            precip_mm: 0.02,
            precip_in: 0,
            humidity: 72,
            cloud: 100,
            feelslike_c: 24.7,
            feelslike_f: 76.4,
            windchill_c: 22.3,
            windchill_f: 72.1,
            heatindex_c: 24.7,
            heatindex_f: 76.4,
            dewpoint_c: 17,
            dewpoint_f: 62.5,
            will_it_rain: 0,
            chance_of_rain: 61,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.5,
            gust_kph: 7.2,
            uv: 5,
          },
          {
            time_epoch: 1701180000,
            time: "2023-11-28 11:00",
            temp_c: 23.4,
            temp_f: 74.1,
            is_day: 1,
            condition: {
              text: "Possibilidade de chuva irregular",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 4.5,
            wind_kph: 7.2,
            wind_degree: 18,
            wind_dir: "NNE",
            pressure_mb: 1017,
            pressure_in: 30.04,
            precip_mm: 0.01,
            precip_in: 0,
            humidity: 66,
            cloud: 86,
            feelslike_c: 25.2,
            feelslike_f: 77.4,
            windchill_c: 23.4,
            windchill_f: 74.1,
            heatindex_c: 25.2,
            heatindex_f: 77.4,
            dewpoint_c: 16.8,
            dewpoint_f: 62.2,
            will_it_rain: 1,
            chance_of_rain: 78,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.5,
            gust_kph: 8.9,
            uv: 5,
          },
          {
            time_epoch: 1701183600,
            time: "2023-11-28 12:00",
            temp_c: 25,
            temp_f: 77.1,
            is_day: 1,
            condition: {
              text: "Parcialmente nublado",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 4.5,
            wind_kph: 7.2,
            wind_degree: 22,
            wind_dir: "NNE",
            pressure_mb: 1017,
            pressure_in: 30.02,
            precip_mm: 0,
            precip_in: 0,
            humidity: 60,
            cloud: 39,
            feelslike_c: 26.3,
            feelslike_f: 79.3,
            windchill_c: 25,
            windchill_f: 77.1,
            heatindex_c: 26.3,
            heatindex_f: 79.3,
            dewpoint_c: 16.8,
            dewpoint_f: 62.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.2,
            gust_kph: 8.3,
            uv: 7,
          },
          {
            time_epoch: 1701187200,
            time: "2023-11-28 13:00",
            temp_c: 26.2,
            temp_f: 79.2,
            is_day: 1,
            condition: {
              text: "Parcialmente nublado",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 4.3,
            wind_kph: 6.8,
            wind_degree: 19,
            wind_dir: "NNE",
            pressure_mb: 1015,
            pressure_in: 29.98,
            precip_mm: 0,
            precip_in: 0,
            humidity: 56,
            cloud: 51,
            feelslike_c: 27.2,
            feelslike_f: 80.9,
            windchill_c: 26.2,
            windchill_f: 79.2,
            heatindex_c: 27.2,
            heatindex_f: 80.9,
            dewpoint_c: 16.7,
            dewpoint_f: 62,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.9,
            gust_kph: 7.9,
            uv: 7,
          },
          {
            time_epoch: 1701190800,
            time: "2023-11-28 14:00",
            temp_c: 26.3,
            temp_f: 79.4,
            is_day: 1,
            condition: {
              text: "Parcialmente nublado",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 3.8,
            wind_kph: 6.1,
            wind_degree: 4,
            wind_dir: "N",
            pressure_mb: 1014,
            pressure_in: 29.95,
            precip_mm: 0,
            precip_in: 0,
            humidity: 55,
            cloud: 36,
            feelslike_c: 27.2,
            feelslike_f: 81,
            windchill_c: 26.3,
            windchill_f: 79.4,
            heatindex_c: 27.2,
            heatindex_f: 81,
            dewpoint_c: 16.6,
            dewpoint_f: 61.9,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.9,
            gust_kph: 8,
            uv: 7,
          },
          {
            time_epoch: 1701194400,
            time: "2023-11-28 15:00",
            temp_c: 25.9,
            temp_f: 78.7,
            is_day: 1,
            condition: {
              text: "Parcialmente nublado",
              icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
              code: 1003,
            },
            wind_mph: 4,
            wind_kph: 6.5,
            wind_degree: 348,
            wind_dir: "NNW",
            pressure_mb: 1013,
            pressure_in: 29.92,
            precip_mm: 0,
            precip_in: 0,
            humidity: 57,
            cloud: 34,
            feelslike_c: 26.9,
            feelslike_f: 80.5,
            windchill_c: 25.9,
            windchill_f: 78.7,
            heatindex_c: 26.9,
            heatindex_f: 80.5,
            dewpoint_c: 16.8,
            dewpoint_f: 62.2,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.9,
            gust_kph: 9.4,
            uv: 7,
          },
          {
            time_epoch: 1701198000,
            time: "2023-11-28 16:00",
            temp_c: 25.3,
            temp_f: 77.6,
            is_day: 1,
            condition: {
              text: "Possibilidade de chuva irregular",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 3.4,
            wind_kph: 5.4,
            wind_degree: 330,
            wind_dir: "NNW",
            pressure_mb: 1013,
            pressure_in: 29.9,
            precip_mm: 0.08,
            precip_in: 0,
            humidity: 62,
            cloud: 70,
            feelslike_c: 26.6,
            feelslike_f: 79.8,
            windchill_c: 25.3,
            windchill_f: 77.6,
            heatindex_c: 26.6,
            heatindex_f: 79.8,
            dewpoint_c: 17.5,
            dewpoint_f: 63.5,
            will_it_rain: 1,
            chance_of_rain: 88,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 5.3,
            gust_kph: 8.5,
            uv: 6,
          },
          {
            time_epoch: 1701201600,
            time: "2023-11-28 17:00",
            temp_c: 24.1,
            temp_f: 75.3,
            is_day: 1,
            condition: {
              text: "Possibilidade de chuva irregular",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 2,
            wind_kph: 3.2,
            wind_degree: 333,
            wind_dir: "NNW",
            pressure_mb: 1012,
            pressure_in: 29.9,
            precip_mm: 0.07,
            precip_in: 0,
            humidity: 71,
            cloud: 79,
            feelslike_c: 25.7,
            feelslike_f: 78.3,
            windchill_c: 24.1,
            windchill_f: 75.3,
            heatindex_c: 25.7,
            heatindex_f: 78.3,
            dewpoint_c: 18.5,
            dewpoint_f: 65.2,
            will_it_rain: 1,
            chance_of_rain: 72,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.6,
            gust_kph: 5.8,
            uv: 5,
          },
          {
            time_epoch: 1701205200,
            time: "2023-11-28 18:00",
            temp_c: 23.2,
            temp_f: 73.7,
            is_day: 1,
            condition: {
              text: "Possibilidade de chuva irregular",
              icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
              code: 1063,
            },
            wind_mph: 0.9,
            wind_kph: 1.4,
            wind_degree: 12,
            wind_dir: "NNE",
            pressure_mb: 1012,
            pressure_in: 29.89,
            precip_mm: 0.01,
            precip_in: 0,
            humidity: 76,
            cloud: 75,
            feelslike_c: 25.2,
            feelslike_f: 77.3,
            windchill_c: 23.2,
            windchill_f: 73.7,
            heatindex_c: 25.2,
            heatindex_f: 77.3,
            dewpoint_c: 18.8,
            dewpoint_f: 65.8,
            will_it_rain: 1,
            chance_of_rain: 71,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 1.7,
            gust_kph: 2.8,
            uv: 5,
          },
          {
            time_epoch: 1701208800,
            time: "2023-11-28 19:00",
            temp_c: 23.6,
            temp_f: 74.5,
            is_day: 0,
            condition: {
              text: "Parcialmente nublado",
              icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
              code: 1003,
            },
            wind_mph: 1.8,
            wind_kph: 2.9,
            wind_degree: 9,
            wind_dir: "N",
            pressure_mb: 1012,
            pressure_in: 29.89,
            precip_mm: 0,
            precip_in: 0,
            humidity: 80,
            cloud: 44,
            feelslike_c: 25.6,
            feelslike_f: 78,
            windchill_c: 23.6,
            windchill_f: 74.5,
            heatindex_c: 25.6,
            heatindex_f: 78,
            dewpoint_c: 19.9,
            dewpoint_f: 67.8,
            will_it_rain: 0,
            chance_of_rain: 0,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.1,
            gust_kph: 5,
            uv: 1,
          },
          {
            time_epoch: 1701212400,
            time: "2023-11-28 20:00",
            temp_c: 21.8,
            temp_f: 71.3,
            is_day: 0,
            condition: {
              text: "Possibilidade de chuva irregular",
              icon: "//cdn.weatherapi.com/weather/64x64/night/176.png",
              code: 1063,
            },
            wind_mph: 0.9,
            wind_kph: 1.4,
            wind_degree: 11,
            wind_dir: "NNE",
            pressure_mb: 1013,
            pressure_in: 29.91,
            precip_mm: 0.33,
            precip_in: 0.01,
            humidity: 88,
            cloud: 81,
            feelslike_c: 21.8,
            feelslike_f: 71.3,
            windchill_c: 21.8,
            windchill_f: 71.3,
            heatindex_c: 24.4,
            heatindex_f: 76,
            dewpoint_c: 19.7,
            dewpoint_f: 67.5,
            will_it_rain: 0,
            chance_of_rain: 57,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 9,
            vis_miles: 5,
            gust_mph: 1.8,
            gust_kph: 2.9,
            uv: 1,
          },
          {
            time_epoch: 1701216000,
            time: "2023-11-28 21:00",
            temp_c: 20.8,
            temp_f: 69.5,
            is_day: 0,
            condition: {
              text: "Aguaceiros fracos",
              icon: "//cdn.weatherapi.com/weather/64x64/night/353.png",
              code: 1240,
            },
            wind_mph: 1.1,
            wind_kph: 1.8,
            wind_degree: 265,
            wind_dir: "W",
            pressure_mb: 1014,
            pressure_in: 29.95,
            precip_mm: 1,
            precip_in: 0.04,
            humidity: 93,
            cloud: 88,
            feelslike_c: 20.8,
            feelslike_f: 69.5,
            windchill_c: 20.8,
            windchill_f: 69.5,
            heatindex_c: 20.8,
            heatindex_f: 69.5,
            dewpoint_c: 19.7,
            dewpoint_f: 67.4,
            will_it_rain: 0,
            chance_of_rain: 65,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 2.3,
            gust_kph: 3.7,
            uv: 1,
          },
          {
            time_epoch: 1701219600,
            time: "2023-11-28 22:00",
            temp_c: 20.9,
            temp_f: 69.6,
            is_day: 0,
            condition: {
              text: "Aguaceiros fracos",
              icon: "//cdn.weatherapi.com/weather/64x64/night/353.png",
              code: 1240,
            },
            wind_mph: 2.2,
            wind_kph: 3.6,
            wind_degree: 228,
            wind_dir: "SW",
            pressure_mb: 1015,
            pressure_in: 29.97,
            precip_mm: 1.11,
            precip_in: 0.04,
            humidity: 94,
            cloud: 79,
            feelslike_c: 20.9,
            feelslike_f: 69.6,
            windchill_c: 20.9,
            windchill_f: 69.6,
            heatindex_c: 20.9,
            heatindex_f: 69.6,
            dewpoint_c: 19.8,
            dewpoint_f: 67.7,
            will_it_rain: 0,
            chance_of_rain: 57,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 4.2,
            gust_kph: 6.8,
            uv: 1,
          },
          {
            time_epoch: 1701223200,
            time: "2023-11-28 23:00",
            temp_c: 20.5,
            temp_f: 68.9,
            is_day: 0,
            condition: {
              text: "Aguaceiros fracos",
              icon: "//cdn.weatherapi.com/weather/64x64/night/353.png",
              code: 1240,
            },
            wind_mph: 2.2,
            wind_kph: 3.6,
            wind_degree: 183,
            wind_dir: "S",
            pressure_mb: 1015,
            pressure_in: 29.99,
            precip_mm: 2.12,
            precip_in: 0.08,
            humidity: 96,
            cloud: 67,
            feelslike_c: 20.5,
            feelslike_f: 68.9,
            windchill_c: 20.5,
            windchill_f: 68.9,
            heatindex_c: 20.5,
            heatindex_f: 68.9,
            dewpoint_c: 19.8,
            dewpoint_f: 67.7,
            will_it_rain: 0,
            chance_of_rain: 53,
            will_it_snow: 0,
            chance_of_snow: 0,
            vis_km: 10,
            vis_miles: 6,
            gust_mph: 3.9,
            gust_kph: 6.3,
            uv: 1,
          },
        ],
      },
    ],
  },
};
